#!/bin/bash

################################################################################
## ENVIRONMENTs
################################################################################
INSTALL_DIR=${HOME}
# MISC_DIR=${0%/*}
# echo "scriptPath0: "$(cd `dirname $0`; pwd)
# echo "scriptPath1: "$(dirname $(readlink -f $0))
# echo "scriptPath2: "$(cd $(dirname ${BASH_SOURCE:-$0});pwd)
MISC_DIR=$(dirname $(readlink -f $0))

echo "src "${MISC_DIR}
echo "dst "${INSTALL_DIR}

################################################################################
## VIM
################################################################################
[ -e ${INSTALL_DIR}/.vim ]      && rm -rf ${INSTALL_DIR}/.vim
[ -e ${INSTALL_DIR}/.vimrc ]    && rm -rf ${INSTALL_DIR}/.vimrc
[ -L ${INSTALL_DIR}/.vim ]      && rm -rf ${INSTALL_DIR}/.vim
[ -L ${INSTALL_DIR}/.vimrc ]    && rm -rf ${INSTALL_DIR}/.vimrc

ln -s ${MISC_DIR}/vim           ${INSTALL_DIR}/.vim
ln -s ${MISC_DIR}/vim/.vimrc    ${INSTALL_DIR}/.vimrc

################################################################################
## SH COMMON
################################################################################
[ -e ${INSTALL_DIR}/.common.sh ]   && rm -rf ${INSTALL_DIR}/.common.sh
[ -L ${INSTALL_DIR}/.common.sh ]   && rm -rf ${INSTALL_DIR}/.common.sh
ln -s ${MISC_DIR}/sh/.common.sh    ${INSTALL_DIR}/.common.sh

[ -e ${INSTALL_DIR}/.env.sh ]   && rm -rf ${INSTALL_DIR}/.env.sh
[ -L ${INSTALL_DIR}/.env.sh ]   && rm -rf ${INSTALL_DIR}/.env.sh
ln -s ${MISC_DIR}/sh/.env.sh    ${INSTALL_DIR}/.env.sh

[ -e ${INSTALL_DIR}/.functions.sh ]   && rm -rf ${INSTALL_DIR}/.functions.sh
[ -L ${INSTALL_DIR}/.functions.sh ]   && rm -rf ${INSTALL_DIR}/.functions.sh
ln -s ${MISC_DIR}/sh/.functions.sh    ${INSTALL_DIR}/.functions.sh

################################################################################
## ZSH
################################################################################
[ -e ${INSTALL_DIR}/.oh-my-zsh ]    && rm -rf ${INSTALL_DIR}/.oh-my-zsh
[ -L ${INSTALL_DIR}/.oh-my-zsh ]    && rm -rf ${INSTALL_DIR}/.oh-my-zsh
ln -s ${MISC_DIR}/sh/.oh-my-zsh     ${INSTALL_DIR}/.oh-my-zsh

[ -e ${INSTALL_DIR}/.zshrc ]        && rm -rf ${INSTALL_DIR}/.zshrc
[ -L ${INSTALL_DIR}/.zshrc ]        && rm -rf ${INSTALL_DIR}/.zshrc
ln -s ${MISC_DIR}/sh/.zshrc         ${INSTALL_DIR}/.zshrc

################################################################################
## BASH
################################################################################
[ -e ${INSTALL_DIR}/.bashrc ]   && rm -rf ${INSTALL_DIR}/.bashrc
[ -L ${INSTALL_DIR}/.bashrc ]   && rm -rf ${INSTALL_DIR}/.bashrc
ln -s ${MISC_DIR}/sh/.bashrc    ${INSTALL_DIR}/.bashrc
